Dbt_Demo:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      schema: DEMO_SCHEMA
      database: DBT_PROJECT_DB
      account: ''
      user: ''
